import time

# Class that handles helper functions
class Utils:
    # Gather the current date and time. Returns the following:
    #
    #   ["MM/DD/YYYY", "HH:MM:SS [AM|PM]"]
    def get_current_date_and_time(self):
        curr_time = time.time()
        local_time = time.localtime(curr_time)
        date = str(local_time.tm_mon) + "/" + str(local_time.tm_mday) + \
                "/" + str(local_time.tm_year)
        hour = local_time.tm_hour
        if hour > 12:
            hour = hour - 12
            ampm = "PM"
        elif hour == 12:
            ampm = "PM"
        else:
            ampm = "AM"

        minutes = local_time.tm_min
        seconds = local_time.tm_sec

        actual_time = ""
        if hour < 10:
            actual_time = "0" + str(hour) + ":"
        else:
            actual_time = str(hour) + ":"

        if minutes < 10:
            actual_time = actual_time + "0" + str(minutes) + ":"
        else:
            actual_time = actual_time + str(minutes) + ":"

        if seconds < 10:
            actual_time = actual_time + "0" + str(seconds)
        else:
            actual_time = actual_time + str(seconds)

        actual_time = actual_time + " " + ampm

        final_time_stamp = ["Date: " + date, "Time: " + actual_time]
        return final_time_stamp

    # Generate a comment for auto generated files.
    def auto_generated_file_comment(self, collector_name):
        comment = "# This file was auto-generated by the OMV push notification " + collector_name + " collector.\n"
        comment = comment + "# Do NOT modify it.\n"
        time_info = self.get_current_date_and_time()
        comment = comment + "#   " + time_info[0] + "\n"
        comment = comment + "#   " + time_info[1] + "\n#\n"

        return comment